FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8

# Pack
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        tar \
    && rm -rf /var/lib/apt/lists/*

# Copy JDK 8u121
COPY jdk-8u121-linux-x64.tar.gz /tmp/

RUN mkdir -p /opt/java \
    && tar -xzf /tmp/jdk-8u121-linux-x64.tar.gz -C /opt/java --strip-components=1 \
    && rm /tmp/jdk-8u121-linux-x64.tar.gz

ENV JAVA_HOME=/opt/java
ENV PATH=$JAVA_HOME/bin:$PATH

# Download Tomcat 8.5.93
COPY apache-tomcat-8.5.93.tar.gz /tmp/

RUN mkdir -p /opt/tomcat \
    && tar -xzf /tmp/apache-tomcat-8.5.93.tar.gz -C /opt/tomcat --strip-components=1 \
    && rm /tmp/apache-tomcat-8.5.93.tar.gz

ENV CATALINA_HOME=/opt/tomcat
ENV PATH=$CATALINA_HOME/bin:$PATH

# Tomcat user
RUN groupadd -r tomcat \
 && useradd -r -g tomcat -d /opt/tomcat tomcat \
 && chown -R tomcat:tomcat /opt/java /opt/tomcat

USER tomcat

# Deploy
RUN rm -rf /opt/tomcat/webapps/*
ADD App/target/VulnApp.war /opt/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh", "run"]
