FROM tomcat:8-jre8

RUN rm -rf /usr/local/tomcat/webapps/*
ADD App/target/VulnApp.war /usr/local/tomcat/webapps/ROOT.war
RUN echo 'export CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.jndi.ldap.object.trustURLCodebase=true"' > /usr/local/tomcat/bin/setenv.sh \
    && chmod +x /usr/local/tomcat/bin/setenv.sh
EXPOSE 8080 
CMD ["catalina.sh", "run"]